### ISSUE TITLE
How to get the market capitalisation of a specific stock?

### ISSUE THREAD

**Issue by extremewaysback** [hongtaocai/googlefinance#10]
How to get the market capitalisation of a specific stock?

**Comment by hongtaocai** [comment]
sorry there is no such functionality at this moment.

On Thursday, March 31, 2016, Ibelin Gan notifications@github.com wrote:

> How to get the market capitalisation of a specific stock?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hongtaocai/googlefinance/issues/10

## 

Sent from Gmail Mobile
