### ISSUE TITLE
Bug working with Django

### ISSUE THREAD

**Issue by wynnsu** [hongtaocai/googlefinance#5]
In Django view:
![google2](https://cloud.githubusercontent.com/assets/6910730/11613030/fab18228-9bc6-11e5-9298-4e03f3ce4c7e.jpg)
Result:
![google](https://cloud.githubusercontent.com/assets/6910730/11613032/0007a824-9bc7-11e5-9972-54dceff3efe5.jpg)
When calling getQuotes() with object attribute (stock.symbol), the function returns the result of getQuotes('G') which should be getQuotes('GOOG'). Same thing with 'FB', 'AAPL' etc. Only the last letter was passed.

![google3](https://cloud.githubusercontent.com/assets/6910730/11613050/cf8c2afc-9bc7-11e5-8112-1e85acd4030a.jpg)
![google4](https://cloud.githubusercontent.com/assets/6910730/11613051/d131dbf4-9bc7-11e5-9f97-ac84456243e7.jpg)

**Comment by hongtaocai** [comment]
It would be great if you could print out the stock.symbol variable before the append statement and the if statement. If stock.symbol is indeed just 'G', perhaps the package is fine and your django program ignores the previous part of the string.

**Comment by wynnsu** [comment]
The  'Symbol' column in Review screenshot is the value of stock.symbol. And that appears to be 'GOOG'.

**Comment by wynnsu** [comment]
Hi hongtaocai,

Problem solved by using **str**() function. Still don't know where it went wrong but thanks all the same:)
![image](https://cloud.githubusercontent.com/assets/6910730/11760233/c8c61bea-a047-11e5-9ef0-48b6eac9d76a.png)
