### ISSUE TITLE
Unable to fetch FX data

### ISSUE THREAD

**Issue by sheep-farming** [hongtaocai/googlefinance#6]
Tried `googlefinance.getQuotes('CURRENCY:CNY')` but returned all `u''`.
Also cross-rates using the ticker name on the website e.g.: `CNYGBP`/ `CNYHKD` always return `400`,
Is there any mistake in calling it? Thanks a lot.

**Comment by hongtaocai** [comment]
sorry i guess the answer is that my google finance api simply doesn't support currencies.
